# Data
path: "C:\\Users\\Faisal\\Downloads\\Internship summer 2024\\August new images w updates from disi\\Data 9\\Data"
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [23, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 2, 1, 5, 6, 3, 4, 7, 8, 10, 9, 12, 11, 15, 16, 13, 14, 19, 20, 17, 18, 21, 22]

# Classes
names:
  0: Pig








